# Runs when starting zsh, mainly used for environmental variables.
# For main configuration probably use .zshrc

# Change zsh configuration directory
export ZDOTDIR="$HOME/.config/zsh"
export ZPLUG_HOME="$HOME/.config/zsh/zplug"

# Default programs
export EDITOR="nvim"


# vi:syntax=config 
