# Runs when starting zsh, mainly used for environmental variables.
# For main configuration probably use .zshrc

#export TERM=xterm-256color

# Change zsh configuration directory
export ZDOTDIR="$HOME/.config/zsh"
export ZPLUG_HOME="$HOME/.config/zsh/zplug"

# Default programs
export EDITOR="nvim"

# WeeChat
export WEECHAT_HOME="$HOME/.config/weechat"


# vi:syntax=config 
